### ISSUE TITLE
How to overfit a single image

### ISSUE THREAD

**Issue by jorgejgnz** [cloneofsimo/minDiffusion#3]
I'm having the following samples after training:

- 200 epochs for 1 CELEBA image
![ddpm_1img_200epochs](https://user-images.githubusercontent.com/60674219/195911759-49cbdea3-4642-4b9c-a94f-b5bdf0fc82ba.png)

- 100 epochs for 1000 CELEBA images 
![ddpm_1000imgs_100epochs](https://user-images.githubusercontent.com/60674219/195911798-af59dc02-4be8-4764-9400-6a1db899c888.png)

Shouldn't using only 1 image for training make the model to overfit that image in a few epochs and produce always that image for any given z?

Why does using more training samples makes the model to converge faster?

Thank you!

**Comment by cloneofsimo** [comment]
That's interesting. I'm not really sure...

**Comment by willdalh** [comment]
With normal DDPM sampling, some noise correction is added each step (except for the last one) during the reverse process. [See line 4 in algorithm 2 in the DDPM paper](https://arxiv.org/pdf/2006.11239.pdf). I suspect this will make it difficult for the model to always give the same image given this stochasticity.

Another thought is that diffusion models are great at capturing the distribution of a dataset.  With only 1 image, the model has a much smaller space in the data manifold that it tries to reach instead of a greater one.

**Comment by jorgejgnz** [comment]
That makes sense. Thank you!
